/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ILiquidationBurnable, ILiquidationBurnableInterface } from "../../interfaces/ILiquidationBurnable.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "burnForLiquidation",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ILiquidationBurnable__factory {
    static readonly abi = _abi;
    static createInterface(): ILiquidationBurnableInterface {
      return new Interface(_abi) as ILiquidationBurnableInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ILiquidationBurnable {
      return new Contract(address, _abi, runner) as unknown as ILiquidationBurnable;
    }
  }
  