/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ChainlinkOracleInterface extends Interface {
    getFunction(nameOrSignature: "TEMPORARY_OVERRIDE_DURATION" | "decimals" | "description" | "feed" | "getRoundData" | "latestRoundData" | "owner" | "renounceOwnership" | "setTemporaryPrice" | "temporaryPrice" | "temporaryPriceUntil" | "transferOwnership" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'TEMPORARY_OVERRIDE_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'description', values?: undefined): string;
encodeFunctionData(functionFragment: 'feed', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoundData', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'latestRoundData', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setTemporaryPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'temporaryPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'temporaryPriceUntil', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'TEMPORARY_OVERRIDE_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'description', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoundData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestRoundData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTemporaryPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'temporaryPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'temporaryPriceUntil', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ChainlinkOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): ChainlinkOracle;
    waitForDeployment(): Promise<this>;

    interface: ChainlinkOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    TEMPORARY_OVERRIDE_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    description: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    feed: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRoundData: TypedContractMethod<
      [roundId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint]],
      'view'
    >
    

    
    latestRoundData: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setTemporaryPrice: TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    temporaryPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    temporaryPriceUntil: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'TEMPORARY_OVERRIDE_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'description'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'feed'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoundData'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'latestRoundData'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTemporaryPrice'): TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'temporaryPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'temporaryPriceUntil'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }