/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'InterestRateModel', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InterestRateModel__factory>
getContractFactory(name: 'LendingPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LendingPool__factory>
getContractFactory(name: 'ChainlinkOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ChainlinkOracle__factory>
getContractFactory(name: 'LendingPoolStorage', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LendingPoolStorage__factory>
getContractFactory(name: 'MockUSDT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDT__factory>
getContractFactory(name: 'TestChainlinkFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TestChainlinkFeed__factory>
getContractFactory(name: 'ILiquidationBurnable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILiquidationBurnable__factory>
getContractFactory(name: 'IChainlinkOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IChainlinkOracle__factory>

  getContractAt(name: 'InterestRateModel', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InterestRateModel>
getContractAt(name: 'LendingPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LendingPool>
getContractAt(name: 'ChainlinkOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ChainlinkOracle>
getContractAt(name: 'LendingPoolStorage', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LendingPoolStorage>
getContractAt(name: 'MockUSDT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDT>
getContractAt(name: 'TestChainlinkFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TestChainlinkFeed>
getContractAt(name: 'ILiquidationBurnable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILiquidationBurnable>
getContractAt(name: 'IChainlinkOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IChainlinkOracle>

  deployContract(name: 'InterestRateModel', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InterestRateModel>
deployContract(name: 'LendingPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingPool>
deployContract(name: 'ChainlinkOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ChainlinkOracle>
deployContract(name: 'LendingPoolStorage', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingPoolStorage>
deployContract(name: 'MockUSDT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDT>
deployContract(name: 'TestChainlinkFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestChainlinkFeed>
deployContract(name: 'ILiquidationBurnable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILiquidationBurnable>
deployContract(name: 'IChainlinkOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IChainlinkOracle>

  deployContract(name: 'InterestRateModel', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InterestRateModel>
deployContract(name: 'LendingPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingPool>
deployContract(name: 'ChainlinkOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ChainlinkOracle>
deployContract(name: 'LendingPoolStorage', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingPoolStorage>
deployContract(name: 'MockUSDT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDT>
deployContract(name: 'TestChainlinkFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestChainlinkFeed>
deployContract(name: 'ILiquidationBurnable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILiquidationBurnable>
deployContract(name: 'IChainlinkOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IChainlinkOracle>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  