/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface InterestRateModelInterface extends Interface {
    getFunction(nameOrSignature: "BASE_RATE_APY" | "OPTIMAL_UTILIZATION" | "SECONDS_PER_YEAR" | "SLOPE_1_APY" | "SLOPE_2_APY"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'BASE_RATE_APY', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPTIMAL_UTILIZATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'SECONDS_PER_YEAR', values?: undefined): string;
encodeFunctionData(functionFragment: 'SLOPE_1_APY', values?: undefined): string;
encodeFunctionData(functionFragment: 'SLOPE_2_APY', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BASE_RATE_APY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPTIMAL_UTILIZATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SECONDS_PER_YEAR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SLOPE_1_APY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SLOPE_2_APY', data: BytesLike): Result;
  }

  

  export interface InterestRateModel extends BaseContract {
    
    connect(runner?: ContractRunner | null): InterestRateModel;
    waitForDeployment(): Promise<this>;

    interface: InterestRateModelInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_RATE_APY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    OPTIMAL_UTILIZATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SECONDS_PER_YEAR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SLOPE_1_APY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SLOPE_2_APY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_RATE_APY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'OPTIMAL_UTILIZATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SECONDS_PER_YEAR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SLOPE_1_APY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SLOPE_2_APY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }