/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DataTypes {
      
    export type UserAccountDataStruct = {totalCollateralETH: BigNumberish, totalDebtETH: BigNumberish, maxBorrowETH: BigNumberish, healthFactor: BigNumberish, lastUpdateTimestamp: BigNumberish}

    export type UserAccountDataStructOutput = [totalCollateralETH: bigint, totalDebtETH: bigint, maxBorrowETH: bigint, healthFactor: bigint, lastUpdateTimestamp: bigint] & {totalCollateralETH: bigint, totalDebtETH: bigint, maxBorrowETH: bigint, healthFactor: bigint, lastUpdateTimestamp: bigint }
  
    }

  export interface LendingPoolInterface extends Interface {
    getFunction(nameOrSignature: "BASE_RATE_APY" | "BPS" | "BUFFER_TARGET_PERCENT" | "LIQUIDATION_BONUS" | "LIQUIDATION_THRESHOLD" | "LTV" | "MAX_RESERVE_FACTOR" | "MIN_BUFFER" | "MIN_HEALTH_FACTOR" | "OPTIMAL_UTILIZATION" | "ORACLE_HEARTBEAT" | "SECONDS_PER_YEAR" | "SLOPE_1_APY" | "SLOPE_2_APY" | "borrowETH" | "borrowIndex" | "collateralToken" | "collateralTokenDecimals" | "depositCollateral" | "depositETH" | "getAccruedInterest" | "getBorrowRatePerSec" | "getCollateralETHValue" | "getLenderBalance" | "getTotalDebt" | "getUserAccountData" | "getWithdrawableCollateral" | "lastBorrowerUpdateTimestamp" | "lastGlobalUpdateTimestamp" | "lenderDepositShares" | "liquidate" | "liquidityIndex" | "oracleDecimals" | "owner" | "priceOracle" | "principalBorrowed" | "protocolFees" | "renounceOwnership" | "repayETH" | "reserveBuffer" | "reserveFactor" | "setReserveFactor" | "totalBadDebt" | "totalDebt" | "totalEthDeposited" | "transferOwnership" | "userBorrowIndex" | "userCollateral" | "userLiquidityIndex" | "withdrawCollateral" | "withdrawETH" | "withdrawProtocolFees" | "withdrawReserveBuffer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BadDebtCovered" | "Borrow" | "CollateralDeposited" | "CollateralWithdrawn" | "Deposit" | "Liquidated" | "OwnershipTransferred" | "ProtocolFeesWithdrawn" | "Repay" | "ReserveBufferWithdrawn" | "ReserveFactorUpdated" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'BASE_RATE_APY', values?: undefined): string;
encodeFunctionData(functionFragment: 'BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'BUFFER_TARGET_PERCENT', values?: undefined): string;
encodeFunctionData(functionFragment: 'LIQUIDATION_BONUS', values?: undefined): string;
encodeFunctionData(functionFragment: 'LIQUIDATION_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'LTV', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_RESERVE_FACTOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_BUFFER', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_HEALTH_FACTOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPTIMAL_UTILIZATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_HEARTBEAT', values?: undefined): string;
encodeFunctionData(functionFragment: 'SECONDS_PER_YEAR', values?: undefined): string;
encodeFunctionData(functionFragment: 'SLOPE_1_APY', values?: undefined): string;
encodeFunctionData(functionFragment: 'SLOPE_2_APY', values?: undefined): string;
encodeFunctionData(functionFragment: 'borrowETH', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'borrowIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'collateralToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'collateralTokenDecimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositCollateral', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAccruedInterest', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getBorrowRatePerSec', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCollateralETHValue', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLenderBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalDebt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserAccountData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWithdrawableCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastBorrowerUpdateTimestamp', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastGlobalUpdateTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'lenderDepositShares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'liquidate', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'liquidityIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracleDecimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceOracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'principalBorrowed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'protocolFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'repayETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'reserveBuffer', values?: undefined): string;
encodeFunctionData(functionFragment: 'reserveFactor', values?: undefined): string;
encodeFunctionData(functionFragment: 'setReserveFactor', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalBadDebt', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalDebt', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEthDeposited', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userBorrowIndex', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userLiquidityIndex', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawCollateral', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawETH', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawProtocolFees', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawReserveBuffer', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BASE_RATE_APY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BUFFER_TARGET_PERCENT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LIQUIDATION_BONUS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LIQUIDATION_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LTV', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_RESERVE_FACTOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_BUFFER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_HEALTH_FACTOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPTIMAL_UTILIZATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_HEARTBEAT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SECONDS_PER_YEAR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SLOPE_1_APY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SLOPE_2_APY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrowETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrowIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collateralToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collateralTokenDecimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccruedInterest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowRatePerSec', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCollateralETHValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLenderBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserAccountData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWithdrawableCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastBorrowerUpdateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastGlobalUpdateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lenderDepositShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracleDecimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'principalBorrowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveBuffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveFactor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReserveFactor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBadDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEthDeposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userBorrowIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userLiquidityIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawProtocolFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawReserveBuffer', data: BytesLike): Result;
  }

  
    export namespace BadDebtCoveredEvent {
      export type InputTuple = [amountCovered: BigNumberish, remainingBadDebt: BigNumberish];
      export type OutputTuple = [amountCovered: bigint, remainingBadDebt: bigint];
      export interface OutputObject {amountCovered: bigint, remainingBadDebt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BorrowEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CollateralDepositedEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CollateralWithdrawnEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [lender: string, amount: bigint];
      export interface OutputObject {lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidatedEvent {
      export type InputTuple = [borrower: AddressLike, liquidator: AddressLike, debtRepaid: BigNumberish, collateralSeized: BigNumberish];
      export type OutputTuple = [borrower: string, liquidator: string, debtRepaid: bigint, collateralSeized: bigint];
      export interface OutputObject {borrower: string, liquidator: string, debtRepaid: bigint, collateralSeized: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProtocolFeesWithdrawnEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepayEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReserveBufferWithdrawnEvent {
      export type InputTuple = [admin: AddressLike, amount: BigNumberish];
      export type OutputTuple = [admin: string, amount: bigint];
      export interface OutputObject {admin: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReserveFactorUpdatedEvent {
      export type InputTuple = [newFactor: BigNumberish];
      export type OutputTuple = [newFactor: bigint];
      export interface OutputObject {newFactor: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [lender: string, amount: bigint];
      export interface OutputObject {lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LendingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): LendingPool;
    waitForDeployment(): Promise<this>;

    interface: LendingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_RATE_APY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BUFFER_TARGET_PERCENT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LIQUIDATION_BONUS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LIQUIDATION_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LTV: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_RESERVE_FACTOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_BUFFER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_HEALTH_FACTOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    OPTIMAL_UTILIZATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ORACLE_HEARTBEAT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SECONDS_PER_YEAR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SLOPE_1_APY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SLOPE_2_APY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    borrowETH: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    borrowIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    collateralToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    collateralTokenDecimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    depositCollateral: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    getAccruedInterest: TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getBorrowRatePerSec: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCollateralETHValue: TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getLenderBalance: TypedContractMethod<
      [lender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getTotalDebt: TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserAccountData: TypedContractMethod<
      [user: AddressLike, ],
      [DataTypes.UserAccountDataStructOutput],
      'view'
    >
    

    
    getWithdrawableCollateral: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lastBorrowerUpdateTimestamp: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lastGlobalUpdateTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lenderDepositShares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    liquidate: TypedContractMethod<
      [borrower: AddressLike, debtToCover: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    liquidityIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracleDecimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    priceOracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    principalBorrowed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    protocolFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    repayETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    reserveBuffer: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reserveFactor: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setReserveFactor: TypedContractMethod<
      [newFactor: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalBadDebt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalDebt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalEthDeposited: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userBorrowIndex: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    userCollateral: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    userLiquidityIndex: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdrawCollateral: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawETH: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawProtocolFees: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawReserveBuffer: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_RATE_APY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BUFFER_TARGET_PERCENT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LIQUIDATION_BONUS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LIQUIDATION_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LTV'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_RESERVE_FACTOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_BUFFER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_HEALTH_FACTOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'OPTIMAL_UTILIZATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_HEARTBEAT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SECONDS_PER_YEAR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SLOPE_1_APY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SLOPE_2_APY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'borrowETH'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'borrowIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'collateralToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'collateralTokenDecimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositCollateral'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getAccruedInterest'): TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBorrowRatePerSec'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCollateralETHValue'): TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLenderBalance'): TypedContractMethod<
      [lender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalDebt'): TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserAccountData'): TypedContractMethod<
      [user: AddressLike, ],
      [DataTypes.UserAccountDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getWithdrawableCollateral'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastBorrowerUpdateTimestamp'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastGlobalUpdateTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lenderDepositShares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liquidate'): TypedContractMethod<
      [borrower: AddressLike, debtToCover: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'liquidityIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracleDecimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'priceOracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'principalBorrowed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'protocolFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repayETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'reserveBuffer'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reserveFactor'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setReserveFactor'): TypedContractMethod<
      [newFactor: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalBadDebt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalDebt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalEthDeposited'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userBorrowIndex'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userCollateral'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userLiquidityIndex'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawCollateral'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawETH'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawProtocolFees'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawReserveBuffer'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BadDebtCovered'): TypedContractEvent<BadDebtCoveredEvent.InputTuple, BadDebtCoveredEvent.OutputTuple, BadDebtCoveredEvent.OutputObject>;
getEvent(key: 'Borrow'): TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
getEvent(key: 'CollateralDeposited'): TypedContractEvent<CollateralDepositedEvent.InputTuple, CollateralDepositedEvent.OutputTuple, CollateralDepositedEvent.OutputObject>;
getEvent(key: 'CollateralWithdrawn'): TypedContractEvent<CollateralWithdrawnEvent.InputTuple, CollateralWithdrawnEvent.OutputTuple, CollateralWithdrawnEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'Liquidated'): TypedContractEvent<LiquidatedEvent.InputTuple, LiquidatedEvent.OutputTuple, LiquidatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProtocolFeesWithdrawn'): TypedContractEvent<ProtocolFeesWithdrawnEvent.InputTuple, ProtocolFeesWithdrawnEvent.OutputTuple, ProtocolFeesWithdrawnEvent.OutputObject>;
getEvent(key: 'Repay'): TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
getEvent(key: 'ReserveBufferWithdrawn'): TypedContractEvent<ReserveBufferWithdrawnEvent.InputTuple, ReserveBufferWithdrawnEvent.OutputTuple, ReserveBufferWithdrawnEvent.OutputObject>;
getEvent(key: 'ReserveFactorUpdated'): TypedContractEvent<ReserveFactorUpdatedEvent.InputTuple, ReserveFactorUpdatedEvent.OutputTuple, ReserveFactorUpdatedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'BadDebtCovered(uint256,uint256)': TypedContractEvent<BadDebtCoveredEvent.InputTuple, BadDebtCoveredEvent.OutputTuple, BadDebtCoveredEvent.OutputObject>;
      BadDebtCovered: TypedContractEvent<BadDebtCoveredEvent.InputTuple, BadDebtCoveredEvent.OutputTuple, BadDebtCoveredEvent.OutputObject>;
    

      'Borrow(address,uint256)': TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
      Borrow: TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
    

      'CollateralDeposited(address,uint256)': TypedContractEvent<CollateralDepositedEvent.InputTuple, CollateralDepositedEvent.OutputTuple, CollateralDepositedEvent.OutputObject>;
      CollateralDeposited: TypedContractEvent<CollateralDepositedEvent.InputTuple, CollateralDepositedEvent.OutputTuple, CollateralDepositedEvent.OutputObject>;
    

      'CollateralWithdrawn(address,uint256)': TypedContractEvent<CollateralWithdrawnEvent.InputTuple, CollateralWithdrawnEvent.OutputTuple, CollateralWithdrawnEvent.OutputObject>;
      CollateralWithdrawn: TypedContractEvent<CollateralWithdrawnEvent.InputTuple, CollateralWithdrawnEvent.OutputTuple, CollateralWithdrawnEvent.OutputObject>;
    

      'Deposit(address,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'Liquidated(address,address,uint256,uint256)': TypedContractEvent<LiquidatedEvent.InputTuple, LiquidatedEvent.OutputTuple, LiquidatedEvent.OutputObject>;
      Liquidated: TypedContractEvent<LiquidatedEvent.InputTuple, LiquidatedEvent.OutputTuple, LiquidatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProtocolFeesWithdrawn(address,uint256)': TypedContractEvent<ProtocolFeesWithdrawnEvent.InputTuple, ProtocolFeesWithdrawnEvent.OutputTuple, ProtocolFeesWithdrawnEvent.OutputObject>;
      ProtocolFeesWithdrawn: TypedContractEvent<ProtocolFeesWithdrawnEvent.InputTuple, ProtocolFeesWithdrawnEvent.OutputTuple, ProtocolFeesWithdrawnEvent.OutputObject>;
    

      'Repay(address,uint256)': TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
      Repay: TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
    

      'ReserveBufferWithdrawn(address,uint256)': TypedContractEvent<ReserveBufferWithdrawnEvent.InputTuple, ReserveBufferWithdrawnEvent.OutputTuple, ReserveBufferWithdrawnEvent.OutputObject>;
      ReserveBufferWithdrawn: TypedContractEvent<ReserveBufferWithdrawnEvent.InputTuple, ReserveBufferWithdrawnEvent.OutputTuple, ReserveBufferWithdrawnEvent.OutputObject>;
    

      'ReserveFactorUpdated(uint256)': TypedContractEvent<ReserveFactorUpdatedEvent.InputTuple, ReserveFactorUpdatedEvent.OutputTuple, ReserveFactorUpdatedEvent.OutputObject>;
      ReserveFactorUpdated: TypedContractEvent<ReserveFactorUpdatedEvent.InputTuple, ReserveFactorUpdatedEvent.OutputTuple, ReserveFactorUpdatedEvent.OutputObject>;
    

      'Withdraw(address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }