/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace LendingPool {
      
    export type UserAccountDataStruct = {totalCollateralETH: BigNumberish, totalDebtETH: BigNumberish, maxBorrowETH: BigNumberish, healthFactor: BigNumberish, lastUpdateTimestamp: BigNumberish}

    export type UserAccountDataStructOutput = [totalCollateralETH: bigint, totalDebtETH: bigint, maxBorrowETH: bigint, healthFactor: bigint, lastUpdateTimestamp: bigint] & {totalCollateralETH: bigint, totalDebtETH: bigint, maxBorrowETH: bigint, healthFactor: bigint, lastUpdateTimestamp: bigint }
  
    }

  export interface LendingPoolInterface extends Interface {
    getFunction(nameOrSignature: "BORROW_RATE_PER_SEC" | "LIQUIDATION_BONUS" | "LIQUIDATION_THRESHOLD" | "LTV" | "RESERVE_FACTOR" | "borrowETH" | "collateralToken" | "depositCollateral" | "depositETH" | "getAccruedInterest" | "getCollateralETHValue" | "getLenderBalance" | "getTotalDebt" | "getUserAccountData" | "getWithdrawableCollateral" | "lastBorrowerUpdateTimestamp" | "lastGlobalUpdateTimestamp" | "lenderDepositShares" | "liquidate" | "liquidityIndex" | "principalBorrowed" | "repayETH" | "reserveBalance" | "totalEthDeposited" | "usdtPriceInEth" | "userCollateral" | "userLiquidityIndex" | "withdrawCollateral" | "withdrawETH"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Borrow" | "CollateralDeposited" | "CollateralWithdrawn" | "Deposit" | "Liquidated" | "Repay" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'BORROW_RATE_PER_SEC', values?: undefined): string;
encodeFunctionData(functionFragment: 'LIQUIDATION_BONUS', values?: undefined): string;
encodeFunctionData(functionFragment: 'LIQUIDATION_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'LTV', values?: undefined): string;
encodeFunctionData(functionFragment: 'RESERVE_FACTOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'borrowETH', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'collateralToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositCollateral', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAccruedInterest', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCollateralETHValue', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLenderBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalDebt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserAccountData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWithdrawableCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastBorrowerUpdateTimestamp', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastGlobalUpdateTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'lenderDepositShares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'liquidate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'liquidityIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'principalBorrowed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'repayETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'reserveBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEthDeposited', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdtPriceInEth', values?: undefined): string;
encodeFunctionData(functionFragment: 'userCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userLiquidityIndex', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawCollateral', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawETH', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BORROW_RATE_PER_SEC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LIQUIDATION_BONUS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LIQUIDATION_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LTV', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RESERVE_FACTOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrowETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collateralToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccruedInterest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCollateralETHValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLenderBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserAccountData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWithdrawableCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastBorrowerUpdateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastGlobalUpdateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lenderDepositShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'principalBorrowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEthDeposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdtPriceInEth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userLiquidityIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawETH', data: BytesLike): Result;
  }

  
    export namespace BorrowEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CollateralDepositedEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CollateralWithdrawnEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [lender: string, amount: bigint];
      export interface OutputObject {lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidatedEvent {
      export type InputTuple = [borrower: AddressLike, liquidator: AddressLike, debtRepaid: BigNumberish, collateralSeized: BigNumberish];
      export type OutputTuple = [borrower: string, liquidator: string, debtRepaid: bigint, collateralSeized: bigint];
      export interface OutputObject {borrower: string, liquidator: string, debtRepaid: bigint, collateralSeized: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepayEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint];
      export interface OutputObject {borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [lender: string, amount: bigint];
      export interface OutputObject {lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LendingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): LendingPool;
    waitForDeployment(): Promise<this>;

    interface: LendingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BORROW_RATE_PER_SEC: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LIQUIDATION_BONUS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LIQUIDATION_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LTV: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RESERVE_FACTOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    borrowETH: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    collateralToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    depositCollateral: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    getAccruedInterest: TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getCollateralETHValue: TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getLenderBalance: TypedContractMethod<
      [lender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getTotalDebt: TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserAccountData: TypedContractMethod<
      [user: AddressLike, ],
      [LendingPool.UserAccountDataStructOutput],
      'view'
    >
    

    
    getWithdrawableCollateral: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lastBorrowerUpdateTimestamp: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lastGlobalUpdateTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lenderDepositShares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    liquidate: TypedContractMethod<
      [borrower: AddressLike, ],
      [void],
      'payable'
    >
    

    
    liquidityIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    principalBorrowed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    repayETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    reserveBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalEthDeposited: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdtPriceInEth: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    userCollateral: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    userLiquidityIndex: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdrawCollateral: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawETH: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BORROW_RATE_PER_SEC'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LIQUIDATION_BONUS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LIQUIDATION_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LTV'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RESERVE_FACTOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'borrowETH'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'collateralToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'depositCollateral'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getAccruedInterest'): TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCollateralETHValue'): TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLenderBalance'): TypedContractMethod<
      [lender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalDebt'): TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserAccountData'): TypedContractMethod<
      [user: AddressLike, ],
      [LendingPool.UserAccountDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getWithdrawableCollateral'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastBorrowerUpdateTimestamp'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastGlobalUpdateTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lenderDepositShares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liquidate'): TypedContractMethod<
      [borrower: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'liquidityIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'principalBorrowed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'repayETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'reserveBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalEthDeposited'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdtPriceInEth'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userCollateral'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userLiquidityIndex'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawCollateral'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawETH'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Borrow'): TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
getEvent(key: 'CollateralDeposited'): TypedContractEvent<CollateralDepositedEvent.InputTuple, CollateralDepositedEvent.OutputTuple, CollateralDepositedEvent.OutputObject>;
getEvent(key: 'CollateralWithdrawn'): TypedContractEvent<CollateralWithdrawnEvent.InputTuple, CollateralWithdrawnEvent.OutputTuple, CollateralWithdrawnEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'Liquidated'): TypedContractEvent<LiquidatedEvent.InputTuple, LiquidatedEvent.OutputTuple, LiquidatedEvent.OutputObject>;
getEvent(key: 'Repay'): TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'Borrow(address,uint256)': TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
      Borrow: TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
    

      'CollateralDeposited(address,uint256)': TypedContractEvent<CollateralDepositedEvent.InputTuple, CollateralDepositedEvent.OutputTuple, CollateralDepositedEvent.OutputObject>;
      CollateralDeposited: TypedContractEvent<CollateralDepositedEvent.InputTuple, CollateralDepositedEvent.OutputTuple, CollateralDepositedEvent.OutputObject>;
    

      'CollateralWithdrawn(address,uint256)': TypedContractEvent<CollateralWithdrawnEvent.InputTuple, CollateralWithdrawnEvent.OutputTuple, CollateralWithdrawnEvent.OutputObject>;
      CollateralWithdrawn: TypedContractEvent<CollateralWithdrawnEvent.InputTuple, CollateralWithdrawnEvent.OutputTuple, CollateralWithdrawnEvent.OutputObject>;
    

      'Deposit(address,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'Liquidated(address,address,uint256,uint256)': TypedContractEvent<LiquidatedEvent.InputTuple, LiquidatedEvent.OutputTuple, LiquidatedEvent.OutputObject>;
      Liquidated: TypedContractEvent<LiquidatedEvent.InputTuple, LiquidatedEvent.OutputTuple, LiquidatedEvent.OutputObject>;
    

      'Repay(address,uint256)': TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
      Repay: TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
    

      'Withdraw(address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }