/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface LendingPoolStorageInterface extends Interface {
    getFunction(nameOrSignature: "collateralToken" | "lastBorrowerUpdateTimestamp" | "lastGlobalUpdateTimestamp" | "lenderDepositShares" | "liquidityIndex" | "owner" | "priceOracle" | "principalBorrowed" | "protocolFees" | "renounceOwnership" | "reserveBuffer" | "totalDebt" | "totalEthDeposited" | "transferOwnership" | "userCollateral" | "userLiquidityIndex"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'collateralToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastBorrowerUpdateTimestamp', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastGlobalUpdateTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'lenderDepositShares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'liquidityIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceOracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'principalBorrowed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'protocolFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reserveBuffer', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalDebt', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEthDeposited', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userLiquidityIndex', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'collateralToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastBorrowerUpdateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastGlobalUpdateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lenderDepositShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'principalBorrowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveBuffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEthDeposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userLiquidityIndex', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LendingPoolStorage extends BaseContract {
    
    connect(runner?: ContractRunner | null): LendingPoolStorage;
    waitForDeployment(): Promise<this>;

    interface: LendingPoolStorageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    collateralToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lastBorrowerUpdateTimestamp: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lastGlobalUpdateTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lenderDepositShares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    liquidityIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    priceOracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    principalBorrowed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    protocolFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reserveBuffer: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalDebt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalEthDeposited: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userCollateral: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    userLiquidityIndex: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'collateralToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastBorrowerUpdateTimestamp'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastGlobalUpdateTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lenderDepositShares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liquidityIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'priceOracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'principalBorrowed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'protocolFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reserveBuffer'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalDebt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalEthDeposited'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userCollateral'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userLiquidityIndex'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }