/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { InterestRateModel, InterestRateModelInterface } from "../InterestRateModel.js";

  const _abi = [
  {
    "inputs": [],
    "name": "BASE_RATE_APY",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "OPTIMAL_UTILIZATION",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SECONDS_PER_YEAR",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SLOPE_1_APY",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SLOPE_2_APY",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class InterestRateModel__factory {
    static readonly abi = _abi;
    static createInterface(): InterestRateModelInterface {
      return new Interface(_abi) as InterestRateModelInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): InterestRateModel {
      return new Contract(address, _abi, runner) as unknown as InterestRateModel;
    }
  }
  