/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockChainlinkOracle, MockChainlinkOracleInterface } from "../MockChainlinkOracle.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "initialPrice",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "newPrice",
        "type": "int256"
      }
    ],
    "name": "setPrice",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5060405161027f38038061027f8339818101604052810190602e91906072565b805f8190555042600181905550506098565b5f5ffd5b5f819050919050565b6054816044565b8114605d575f5ffd5b50565b5f81519050606c81604d565b92915050565b5f6020828403121560845760836040565b5b5f608f848285016060565b91505092915050565b6101da806100a55f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063f7a3080614610038578063feaf968c14610054575b5f5ffd5b610052600480360381019061004d91906100dd565b610076565b005b61005c610086565b60405161006d959493929190610153565b60405180910390f35b805f819055504260018190555050565b5f5f5f5f5f60015f545f6001546001945094509450945094509091929394565b5f5ffd5b5f819050919050565b6100bc816100aa565b81146100c6575f5ffd5b50565b5f813590506100d7816100b3565b92915050565b5f602082840312156100f2576100f16100a6565b5b5f6100ff848285016100c9565b91505092915050565b5f69ffffffffffffffffffff82169050919050565b61012681610108565b82525050565b610135816100aa565b82525050565b5f819050919050565b61014d8161013b565b82525050565b5f60a0820190506101665f83018861011d565b610173602083018761012c565b6101806040830186610144565b61018d6060830185610144565b61019a608083018461011d565b969550505050505056fea2646970667358221220a509eac35d47f7aa0c0fb8cd22608f59b2213055f2ab0fdc31ff414838e2f4dc64736f6c63430008220033";

  
      type MockChainlinkOracleConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockChainlinkOracleConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockChainlinkOracle__factory extends ContractFactory {
    
      constructor(...args: MockChainlinkOracleConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(initialPrice, overrides || {});
    };
    override deploy(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(initialPrice, overrides || {}) as Promise<MockChainlinkOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockChainlinkOracle__factory {
      return super.connect(runner) as MockChainlinkOracle__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockChainlinkOracleInterface {
      return new Interface(_abi) as MockChainlinkOracleInterface;
    }
    
    override attach(address: string | Addressable): MockChainlinkOracle {
      return super.attach(address) as MockChainlinkOracle;
    }
  static connect(address: string, runner?: ContractRunner | null): MockChainlinkOracle {
      return new Contract(address, _abi, runner) as unknown as MockChainlinkOracle;
    }
  }

  
  