/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IChainlinkOracle } from './IChainlinkOracle.js';
export type { ILiquidationBurnable } from './ILiquidationBurnable.js';