/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iChainlinkOracleSol from './IChainlinkOracle.sol/index.js';
export type { iChainlinkOracleSol };